"use client";

import type { Metadata } from "next";
import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const disabledNavbar = ["/login", "/register"];

export default function RootLayout({ children }: LayoutProps<"/">) {
  const [state, setState] = React.useState(0);
  const pathname = usePathname();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="">
        {!disabledNavbar.includes(pathname) && <Navbar />}
        {/* <h1>My App {state}</h1>
        <button onClick={() => setState(state + 1)}>click</button> */}
        {children}
      </body>
    </html>
  );
}
